added warehouses field
maaqib121/adulisApi pull request #4
Opened 2023-09-26 09:59 UTC by Mr-Bilal-Ashraf

2023-09-28 10:09 UTC, maaqib121 requested changes

2023-09-28 10:09 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +        if len(value) == 0:
Not an appropriate validation. We must ensure that user has filled the available_qty across all warehouses and the product stock objects in the payload are unique and not be duplicated.

2023-09-28 10:09 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +    def validate(self, attrs):
Why are these validations needed here?

2023-09-28 10:09 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            self.fields["id"].read_only = False
Since `product` and `warehouse` can't be updated, they must be popped out

2023-09-28 10:27 UTC, Mr-Bilal-Ashraf commented on products/api/v1/seller/serializers.py
> +            self.fields["id"].read_only = False
I make `id` writable, because i need it for data validation in validate method, if `id` is read_only, it not appears in the fields at the time of validation. And if we use initial_data to get `id`, there will be a list of dictionaries and there is no method we can decide on which dictionary we are currently working.

2023-09-28 10:30 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            self.fields["id"].read_only = False
Since you are not writing a new product stock object, but updating it, you need to use the product stock serializer by passing the product stock instance in it, instead of making id field writable.

2023-10-02 09:00 UTC, maaqib121 requested changes

2023-10-02 09:00 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +                raise serializers.ValidationError('Cannot select warehouse of another seller.')
As we are dealing with multiple warehouses, the message must be clear to the user. e.g.
"One or more selected warehouse does not exists."

2023-10-02 09:00 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +        product_stock_ids.sort()
Why do we need to sort? Remove it please

2023-10-02 09:00 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +        if list(self.instance.productstock_set.values_list("id", flat=True)) != product_stock_ids:
Not an appropriate approach to validate this.

2023-10-02 09:00 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            available_qty = 0
Please revisit this section. Neither the approach is correct nor the logic to update product's `available_qty`

2023-10-02 09:00 UTC, maaqib121 commented on products/models.py
> +        unique_together = ['product', 'warehouse']
Please update this:
`unique_together = (('product', 'warehouse'),)`
It is either a list of lists or a tuple of tuples. There can be multiple unique together groups but that cannot be accommodated using your existing approach.

2023-10-02 13:47 UTC, maaqib121 requested changes

2023-10-02 13:47 UTC, maaqib121 commented on products/models.py
> +        total_available_qty = self.productstock_set.aggregate(total_available_qty=models.Sum('available_qty'))
It can be refactored and done in one line of code as well:
```
self.available_qty = self.productstock_set.aggregate(
    models.Sum('available_qty')
)['available_qty__sum'] or 0
```

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +        product.update_available_qty()
Make sure that we are updating the product's available quantity only at 'Pricing' step. It will be redundant and extra operation to do this on other steps.

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            for product_stock in product_stocks:
Line 445 is redundant, since we can loop like this.
`for product_stock in validated_data.pop('product_stock', []):`

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +                if 'product_stock' in attrs:
This validation is misplaced in this section. This field is required only if the product creation steps are not completed.

**Hint:** It should be under condition of line 310 as it is required only when product isn't created.

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +                if 'warehouses' in attrs:
This validation is misplaced in this section. This field is required only if the product creation steps are not completed.

**Hint:** It should be under condition else block at line 377 as it is required only when product isn't created.

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            for product_stock in value:
Discussed solution not implemented. Don't loop and run 'n' database queries, instead use a simple if else condition.

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            product_stock_ids = {product_stock.get('id', 0) for product_stock in value}
Update this line to:
`product_stock_ids = {product_stock.get('id') for product_stock in value} `

'0' isn't meaningful.

2023-10-02 13:47 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            if 'available_qty' not in product_stock:
We must return errors keeping in view the error structure django follows. The way this is handled, it will return this kind of error:
```
{
    'errors': {
        'available_qty': ['This field is required.']
    }
}
```
which isn't useable and parseable for front end since frontend is sending a list of dicts in `available_stock` key and will not understand `available_qty` key.

2023-10-03 07:12 UTC, Mr-Bilal-Ashraf commented on products/api/v1/seller/serializers.py
> +            if 'available_qty' not in product_stock:
if `ids` don't match in update after creation, it returns the following error,

```
{
    "errors": {
        "product_stock": [
            {
                "product_stock": "Product stock with pk \"74\" does not exist."
            },
            {
                "product_stock": "Product stock with pk \"75\" does not exist."
            }
        ]
    }
}

```
And in case of `available_qty`,

```
{
    "errors": {
        "product_stock": [
            {
                "available_qty": "This field is required."
            },
            {
                "available_qty": "This field may not be blank."
            }
        ]
    }
}
```

2023-10-03 07:22 UTC, Mr-Bilal-Ashraf commented on products/api/v1/seller/serializers.py
> +            if 'available_qty' not in product_stock:
And now it will return error messages in list like following,

```
{
    "errors": {
        "product_stock": [
            {
                "available_qty": [
                    "This field may not be blank."
                ]
            },
            {
                "available_qty": [
                    "This field is required."
                ]
            }
        ]
    }
}
```

2023-10-03 09:30 UTC, maaqib121 requested changes

2023-10-03 09:30 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +                    if product_stock.get('id') not in product_stock_ids:
Explain this validation!

2023-10-03 09:30 UTC, maaqib121 commented on products/api/v1/seller/serializers.py
> +            product_stock_objects = list()
`project_stock_objects` is not an appropriate name. Don't use general names such as `object` unless necessary. Rename this to either `products_stock` or `product_stocks`.

2023-10-03 09:46 UTC, Mr-Bilal-Ashraf commented on products/api/v1/seller/serializers.py
> +                    if product_stock.get('id') not in product_stock_ids:
`if product_stock.get('id'):` is checking if user send the id of object or not..

`if product_stock.get('id') not in product_stock_ids:` is checking if the given stock object belongs to the product.

If the given stock does not belong to the product, it returns following error for that object,
`Product stock with pk 10 does not exist.`

I think we should change it to:
`Product stock with pk 10 does not belong to product.`

Any suggestions.

2023-10-03 22:31 UTC, merged